name: frostrouter
description: "FrostRouter is a library that helps you move from one page to another in Flutter projects. "
version: 0.9.1
homepage: https://github.com/frostaloncode
repository: https://github.com/frostaloncode/frostrouter
documentation: https://github.com/frostaloncode/frostrouter/wiki
example:
  path: example/

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.1"

dependencies:
  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  test: ^1.25.15

flutter:
