name: frostrouter
description: "FrostRouter is a library that helps you move from one page to another in Flutter projects. It is usually used to manage the transitions between pages. It provides an easier-to-use version of Flutter's default navigation system, helping to create a cleaner and more maintainable code structure. FrostRouter makes in-app routing more flexible and organized."
version: 0.9.0
homepage: https://github.com/frostaloncode
repository: https://github.com/frostaloncode/frostrouter
documentation: https://github.com/frostaloncode/frostrouter/wiki

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  test: ^1.25.15

flutter:
